# Generated by Django 5.1.3 on 2024-12-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='liked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
