# Generated by Django 5.1.3 on 2024-12-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_lesson_liked_comment_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked',
            field=models.IntegerField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], null=True),
        ),
    ]
